import { Navbar } from "@/components/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>TIC</title>
      </head>
      <body
        className={inter.className + " bg-muted min-h-screen flex flex-col"}
      >
        <Navbar />
        <div className="text-foreground bg-muted p-8 pt-[120px] flex-grow">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
